# Generated by Django 2.2.7 on 2020-01-02 08:53

import branch.managers.branch_manager
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('city', '0001_initial'),
        ('commodity', '0001_initial'),
        ('region', '0001_initial'),
        ('country', '0001_initial'),
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='system', max_length=512)),
                ('updated_by', models.CharField(default='system', max_length=512)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('name', models.CharField(max_length=255)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='city.City')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.Company')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='country.Country')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='region.Region')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='state.State')),
            ],
            options={
                'db_table': 'branches',
                'unique_together': {('company', 'name')},
            },
            bases=(models.Model, branch.managers.branch_manager.BranchManager),
        ),
        migrations.CreateModel(
            name='BranchTransportMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='system', max_length=512)),
                ('updated_by', models.CharField(default='system', max_length=512)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('transport_mode', models.CharField(choices=[('AI', 'Air-Import'), ('AE', 'Air-Export'), ('FCLI', 'FCL-Import'), ('FCLE', 'FCL-Export'), ('LCLI', 'LCL-Import'), ('LCLE', 'LCL-Export')], default=None, max_length=255)),
                ('container_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('hazardous', models.BooleanField(default=False)),
                ('instant_quotes', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='branch.Branch')),
                ('commodity', models.ManyToManyField(db_table='branch_transport_commodities', to='commodity.Commodity')),
                ('trade_lanes', models.ManyToManyField(db_table='branch_transport_trade_lanes', to='country.Country')),
            ],
            options={
                'db_table': 'branch_transport_modes',
                'unique_together': {('branch', 'transport_mode')},
            },
            bases=(models.Model, branch.managers.branch_manager.BranchTransportManager),
        ),
    ]
