# Generated by Django 2.2.7 on 2020-01-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0001_initial'),
        ('city', '0001_initial'),
        ('state', '0001_initial'),
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='city',
        ),
        migrations.AddField(
            model_name='branch',
            name='city',
            field=models.ManyToManyField(db_table='branch_cities', to='city.City'),
        ),
        migrations.RemoveField(
            model_name='branch',
            name='region',
        ),
        migrations.AddField(
            model_name='branch',
            name='region',
            field=models.ManyToManyField(db_table='branch_regions', to='region.Region'),
        ),
        migrations.RemoveField(
            model_name='branch',
            name='state',
        ),
        migrations.AddField(
            model_name='branch',
            name='state',
            field=models.ManyToManyField(db_table='branch_states', to='state.State'),
        ),
    ]
