# Generated by Django 2.2.7 on 2020-01-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_auto_20200103_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='city',
            field=models.ManyToManyField(blank=True, db_table='branch_cities', to='city.City'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='region',
            field=models.ManyToManyField(blank=True, db_table='branch_regions', to='region.Region'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='state',
            field=models.ManyToManyField(blank=True, db_table='branch_states', to='state.State'),
        ),
    ]
