# Generated by Django 2.2.7 on 2020-01-06 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0001_initial'),
        ('state', '0001_initial'),
        ('city', '0001_initial'),
        ('branch', '0003_auto_20200103_0629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='city',
        ),
        migrations.AddField(
            model_name='branch',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='city.City'),
        ),
        migrations.RemoveField(
            model_name='branch',
            name='region',
        ),
        migrations.AddField(
            model_name='branch',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='region.Region'),
        ),
        migrations.RemoveField(
            model_name='branch',
            name='state',
        ),
        migrations.AddField(
            model_name='branch',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='state.State'),
        ),
        migrations.AlterField(
            model_name='branchtransportmode',
            name='trade_lanes',
            field=models.ManyToManyField(db_table='branch_transport_tarde_lanes', to='country.Country'),
        ),
        migrations.AlterField(
            model_name='branchtransportmode',
            name='transport_mode',
            field=models.CharField(max_length=255),
        ),
    ]
