# Generated by Django 2.2.7 on 2020-01-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
        ('region', '0001_initial'),
        ('state', '0001_initial'),
        ('branch', '0004_auto_20200106_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='city',
        ),
        migrations.AddField(
            model_name='branch',
            name='city',
            field=models.ManyToManyField(blank=True, db_table='branch_cities', to='city.City'),
        ),
        migrations.RemoveField(
            model_name='branch',
            name='region',
        ),
        migrations.AddField(
            model_name='branch',
            name='region',
            field=models.ManyToManyField(blank=True, db_table='branch_regions', to='region.Region'),
        ),
        migrations.RemoveField(
            model_name='branch',
            name='state',
        ),
        migrations.AddField(
            model_name='branch',
            name='state',
            field=models.ManyToManyField(blank=True, db_table='branch_states', to='state.State'),
        ),
        migrations.AlterField(
            model_name='branchtransportmode',
            name='trade_lanes',
            field=models.ManyToManyField(db_table='branch_transport_trade_lanes', to='country.Country'),
        ),
        migrations.AlterField(
            model_name='branchtransportmode',
            name='transport_mode',
            field=models.CharField(choices=[('AI', 'Air-Import'), ('AE', 'Air-Export'), ('FCLI', 'FCL-Import'), ('FCLE', 'FCL-Export'), ('LCLI', 'LCL-Import'), ('LCLE', 'LCL-Export')], default=None, max_length=255),
        ),
    ]
