# Generated by Django 2.2.7 on 2020-01-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0001_initial'),
        ('city', '0001_initial'),
        ('region', '0001_initial'),
        ('branch', '0006_auto_20200106_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='city',
        ),
        migrations.AddField(
            model_name='branch',
            name='city',
            field=models.ManyToManyField(blank=True, db_table='branch_cities', to='city.City'),
        ),
        migrations.RemoveField(
            model_name='branch',
            name='region',
        ),
        migrations.AddField(
            model_name='branch',
            name='region',
            field=models.ManyToManyField(blank=True, db_table='branch_regions', to='region.Region'),
        ),
        migrations.RemoveField(
            model_name='branch',
            name='state',
        ),
        migrations.AddField(
            model_name='branch',
            name='state',
            field=models.ManyToManyField(blank=True, db_table='branch_states', to='state.State'),
        ),
    ]
