# Generated by Django 2.2.5 on 2020-02-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0008_branch_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_head_branch',
            field=models.BooleanField(default=False),
        ),
    ]
