# Generated by Django 2.2.5 on 2020-04-28 15:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0010_auto_20200304_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchtransportmode',
            name='container_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('20GP', '20-GP'), ('40GP', '40-GP'), ('20Flat-Rack', '20-Flat-Rack'), ('40Flat-Rack', '40-Flat-Rack'), ('20OT', '20-OT'), ('40OT', '40-OT'), ('20Reefer', '20-Reefer'), ('40Reefer', '40-Reefer'), ('20Tank', '20-Tank'), ('40HC', '40-HC'), ('45HC', '45-HC')], default=None, max_length=255), blank=True, null=True, size=None),
        ),
    ]
