# Generated by Django 2.2.5 on 2020-08-20 15:59

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0011_auto_20200428_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='maximum_radius',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='maximum_radius_km',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='maximum_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='branch',
            name='maximum_weight_kg',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='minimum_radius',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='minimum_radius_km',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='minimum_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='branch',
            name='minimum_weight_kg',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='radius_unit',
            field=models.CharField(blank=True, choices=[('miles', 'Miles'), ('km', 'KM')], default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('kg', 'KG'), ('tonnes', 'TONS'), ('lbs', 'LBS')], default=None, max_length=255, null=True),
        ),
    ]
