# Generated by Django 2.2.5 on 2020-10-15 10:53

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0012_auto_20200820_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=255),
        ),
    ]
