version: '3.5'

services:
  web:
    image: registry.gitlab.com/freightcrate/freight_quotes_management:web
    container_name: web
    build: .
    volumes:
      - .:/freightcrate
      - static_volume:/freightcrate/static
    env_file:
      - ./cms/.env.beta
    networks:
      - nginx_network

  nginx:
    image: registry.gitlab.com/freightcrate/freight_quotes_management:nginx
    build: ./nginx
    container_name: nginx
    ports:
      - 443:80
    depends_on:
      - web
    volumes:
      - static_volume:/freightcrate/static
    networks:
      - nginx_network
      
networks:  # <-- and here
  nginx_network:
    driver: bridge
  
volumes:
  static_volume:
