version: '3.5'

services:
  web:
    build: .
    command: bash -c "/bin/bash start.sh"
    volumes:
      - .:/freightcrate
      - static_volume:/freightcrate/static
    env_file:
      - ./cms/.env
    networks:
      - nginx_network

  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - web
    volumes:
      - static_volume:/freightcrate/static
    networks:
      - nginx_network
      
networks:  # <-- and here
  nginx_network:
    driver: bridge
  
volumes:
  static_volume:
