# Generated by Django 2.2.7 on 2020-01-02 08:53

import department.managers.department_manager
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='system', max_length=512)),
                ('updated_by', models.CharField(default='system', max_length=512)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('name', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(0, 'Default'), (1, 'Custom')], default=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.Company')),
            ],
            options={
                'db_table': 'departments',
                'unique_together': {('company', 'name')},
            },
            bases=(models.Model, department.managers.department_manager.DepartmentManager),
        ),
    ]
