# Generated by Django 2.2.5 on 2020-09-09 12:48

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=255),
        ),
    ]
