# Generated by Django 2.2.5 on 2020-05-06 10:58

from django.db import migrations, models
import transport.managers.transport_manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='system', max_length=512)),
                ('updated_by', models.CharField(default='system', max_length=512)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('type', models.CharField(choices=[('air_line', 'Airline'), ('ship_line', 'Shipline')], default='air_line', max_length=512)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=5, null=True)),
                ('digit_code', models.CharField(blank=True, max_length=25, null=True)),
                ('agency_code', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'transports',
            },
            bases=(models.Model, transport.managers.transport_manager.TransportManager),
        ),
    ]
