# Generated by Django 2.2.5 on 2020-03-11 05:47

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import product.managers.product_manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '0001_initial'),
        ('port', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='system', max_length=512)),
                ('updated_by', models.CharField(default='system', max_length=512)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=255)),
                ('transport_modes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Air', 'Air'), ('FCL', 'FCL'), ('LCL', 'LCL')], default=None, max_length=255), size=None)),
                ('airports', models.ManyToManyField(blank=True, db_table='product_airports', related_name='product_airports', to='port.Port')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='entity.Entity')),
                ('seaports', models.ManyToManyField(blank=True, db_table='product_seaports', to='port.Port')),
            ],
            options={
                'db_table': 'products',
                'unique_together': {('entity', 'name')},
            },
            bases=(models.Model, product.managers.product_manager.ProductManager),
        ),
    ]
