# Generated by Django 2.2.5 on 2020-01-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_token_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active'), (2, 'Pending')], default=2),
        ),
    ]
