# Generated by Django 2.2.5 on 2020-01-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20200107_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='token_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
