# Generated by Django 2.2.5 on 2020-01-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20200108_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='token_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
