# Generated by Django 2.2.5 on 2020-01-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20200108_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='registration_token',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
