# Generated by Django 2.2.5 on 2020-01-18 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20200109_0850'),
        ('customer', '0002_auto_20200115_1214'),
    ]

    operations = [
    ]
