# Generated by Django 2.2.5 on 2020-01-22 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20200117_0912'),
        ('customer', '0007_merge_20200120_0858'),
        ('customer', '0007_merge_20200118_1629'),
    ]

    operations = [
    ]
