# Generated by Django 2.2.5 on 2020-01-27 12:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import utils.validations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_merge_20200122_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact_no',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, validators=[utils.validations.ContactNumberValidation.validate_contact_no]),
        ),
    ]
