# Generated by Django 2.2.5 on 2020-02-17 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20200127_1228'),
        ('customer', '0009_auto_20200213_0640'),
    ]

    operations = [
    ]
