# Generated by Django 2.2.5 on 2020-04-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20200221_0641'),
        ('customer', '0013_auto_20200403_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitedvendor',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='invitedvendor',
            unique_together={('customer_company', 'email')},
        ),
    ]
