# Generated by Django 2.2.5 on 2020-07-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_auto_20200409_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='forgot_password_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='forgot_password_link',
            field=models.CharField(default=None, max_length=1024, null=True),
        ),
    ]
