# Generated by Django 2.2.5 on 2020-07-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_auto_20200716_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='forgot_password_link',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True),
        ),
    ]
