# Generated by Django 2.2.5 on 2020-08-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_auto_20200723_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_type_other',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(blank=True, choices=[('importer_or_exporter', 'Importer/Exporter'), ('freight_agent', 'Freight Agent'), ('customs_agent', 'Customs Agent'), ('e-commerce_platform', 'E-Commerce Platform'), ('transporter', 'Transporter'), ('other', 'Other')], default=None, max_length=255, null=True),
        ),
    ]
