# Generated by Django 2.2.5 on 2020-08-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_auto_20200827_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='supervisor',
            field=models.ManyToManyField(blank=True, db_table='customer_supervisors', related_name='customers', to='customer.Customer'),
        ),
    ]
