# Generated by Django 2.2.5 on 2020-09-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_auto_20200827_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(blank=True, choices=[('importer_or_exporter', 'Importer/Exporter'), ('freight_agent', 'Freight Agent'), ('customs_agent', 'Customs Agent'), ('e-commerce_platform', 'E-Commerce Platform'), ('transporter', 'Transporter'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
