# Generated by Django 2.2.7 on 2020-01-02 08:53

import company.managers.company_manager
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='system', max_length=512)),
                ('updated_by', models.CharField(default='system', max_length=512)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('name', models.CharField(max_length=512)),
                ('company_type', models.CharField(choices=[('sole_proprietorship', 'Sole Proprietorship'), ('partnership', 'Partnership'), ('llp', 'LLP'), ('pvt_ltd', 'Pvt Ltd'), ('public_ltd', 'Public Ltd')], default='sole_proprietorship', max_length=30)),
                ('industry', models.CharField(max_length=255)),
                ('business_activity', models.CharField(max_length=255)),
                ('iec', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('gst', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(regex='\\d{2}[A-Z]{5}\\d{4}[A-Z]{1}[A-Z\\d]{1}[Z]{1}[A-Z\\d]{1}')])),
                ('pan', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(regex='[A-Za-z]{5}\\d{4}[A-Za-z]{1}')])),
                ('cin', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(21)])),
                ('company_bio', models.TextField(blank=True, null=True)),
                ('company_structure', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor')], default='customer', max_length=20)),
            ],
            options={
                'db_table': 'companies',
                'permissions': (('assign_task', 'Assign task'),),
            },
            bases=(models.Model, company.managers.company_manager.CompanyManager),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='system', max_length=512)),
                ('updated_by', models.CharField(default='system', max_length=512)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('name', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'organizations',
            },
            bases=(models.Model, company.managers.company_manager.CompanyManager),
        ),
        migrations.CreateModel(
            name='CompanyLogisticInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='system', max_length=512)),
                ('updated_by', models.CharField(default='system', max_length=512)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('annaul_logistic_spend_currency', models.CharField(blank=True, default='INR', max_length=5)),
                ('annual_logistic_spend', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('annual_air_shipments', models.PositiveIntegerField(default=0)),
                ('annual_lcl_shipments', models.PositiveIntegerField(default=0)),
                ('annual_fcl_shipments', models.PositiveIntegerField(default=0)),
                ('total_shipments', models.PositiveIntegerField(default=0)),
                ('annual_air_volume', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('annual_lcl_volume', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('annual_fcl_volume', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('incorporation_year', models.PositiveIntegerField(default=0)),
                ('incorporation_number', models.CharField(blank=True, max_length=255)),
                ('annual_revenue_currency', models.CharField(blank=True, default='INR', max_length=5)),
                ('annual_revenue', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
            options={
                'db_table': 'company_logistic_infos',
            },
            bases=(models.Model, company.managers.company_manager.CompanyManager),
        ),
        migrations.AddField(
            model_name='company',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Organization'),
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('name', 'type')},
        ),
    ]
