# Generated by Django 2.2.5 on 2020-01-10 07:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cin',
            field=models.CharField(default=1, max_length=21, validators=[django.core.validators.MinLengthValidator(21), django.core.validators.RegexValidator(regex='^([L|U]{1})([0-9]{5})([A-Z]{2})([0-9]{4})([PLC|PTC]{3})([0-9]{6})$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='gst',
            field=models.CharField(default=1, max_length=15, validators=[django.core.validators.MinLengthValidator(15), django.core.validators.RegexValidator(regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
