# Generated by Django 2.2.5 on 2020-01-15 12:14

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='business_activity_other',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='industry_other',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='business_activity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('manufacturer', 'Manufacturer'), ('supplier', 'Supplier'), ('retailer', 'Retailer'), ('wholesaler', 'Wholesaler'), ('distributor', 'Distributor'), ('trader', 'Trader'), ('service', 'Service'), ('agriculture', 'Agriculture'), ('other', 'Other')], max_length=255), size=None),
        ),
        migrations.AlterField(
            model_name='company',
            name='cin',
            field=models.CharField(default=None, max_length=21, validators=[django.core.validators.MinLengthValidator(21), django.core.validators.RegexValidator(regex='^([L|U]{1})([0-9]{5})([A-Z]{2})([0-9]{4})([PLC|PTC]{3})([0-9]{6})$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='gst',
            field=models.CharField(default=None, max_length=15, validators=[django.core.validators.MinLengthValidator(15), django.core.validators.RegexValidator(regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('consumer_goods_or_fmcg', 'Consumer Goods/FMCG'), ('engineering_and_manufacturing', 'Engineering and Manufacturing'), ('textiles_and_fashion_apparel', 'Textiles and Fashion Apparel'), ('retail', 'Retail'), ('automotive', 'Automotive'), ('electronics', 'Electronics'), ('chemicals', 'Chemicals'), ('healthcare', 'Healthcare'), ('technology', 'Technology'), ('hospitality', 'Hospitality'), ('food_and_beverages', 'Food & Beverages'), ('jewellery', 'Jewellery'), ('renewable_energy_gas_sola_etc', 'Renewable Energy: Gas,Solar etc.'), ('oil_and_gas', 'Oil & Gas'), ('marine', 'Marine'), ('aerospace', 'Aerospace'), ('government_or_defense', 'Government / Defense'), ('other', 'Other')], max_length=255), size=None),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
