# Generated by Django 2.2.5 on 2020-01-17 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20200110_0707'),
        ('company', '0002_auto_20200115_1214'),
    ]

    operations = [
    ]
