# Generated by Django 2.2.5 on 2020-01-20 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20200117_1048'),
        ('company', '0004_auto_20200120_0710'),
    ]

    operations = [
    ]
