# Generated by Django 2.2.5 on 2020-02-06 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_merge_20200120_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cin',
            field=models.CharField(blank=True, max_length=21, null=True, validators=[django.core.validators.MinLengthValidator(21), django.core.validators.RegexValidator(regex='^([L|U]{1})([0-9]{5})([A-Z]{2})([0-9]{4})([PLC|PTC]{3})([0-9]{6})$')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='gst',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.MinLengthValidator(15), django.core.validators.RegexValidator(regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='iec',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='company',
            name='pan',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(regex='[A-Za-z]{5}\\d{4}[A-Za-z]{1}')]),
        ),
    ]
