# Generated by Django 2.2.5 on 2020-02-21 06:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20200206_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companylogisticinfo',
            name='incorporation_number',
        ),
        migrations.RemoveField(
            model_name='companylogisticinfo',
            name='incorporation_year',
        ),
        migrations.AddField(
            model_name='company',
            name='incorporation_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1970), django.core.validators.MaxValueValidator(2020)]),
        ),
    ]
