# Generated by Django 2.2.5 on 2020-07-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20200221_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companylogisticinfo',
            name='annual_logistic_spend',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='companylogisticinfo',
            name='annual_revenue',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10),
        ),
    ]
