# Generated by Django 2.2.5 on 2020-07-15 06:35

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20200709_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companylogisticinfo',
            name='annual_air_volume',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='companylogisticinfo',
            name='annual_fcl_volume',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='companylogisticinfo',
            name='annual_lcl_volume',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='companylogisticinfo',
            name='annual_logistic_spend',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='companylogisticinfo',
            name='annual_revenue',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
