# Generated by Django 2.2.5 on 2020-08-25 12:33

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20200715_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='business_activity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('manufacturer', 'Manufacturer'), ('supplier', 'Supplier'), ('retailer', 'Retailer'), ('wholesaler', 'Wholesaler'), ('distributor', 'Distributor'), ('trader', 'Trader'), ('service', 'Service'), ('agriculture', 'Agriculture'), ('other', 'Other')], max_length=255), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='companylogisticinfo',
            name='annaul_logistic_spend_currency',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='companylogisticinfo',
            name='annual_revenue_currency',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='companylogisticinfo',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
    ]
