# Generated by Django 2.2.5 on 2020-09-08 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20200904_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=512, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z\\w]+$')]),
        ),
    ]
