# Generated by Django 2.2.5 on 2020-09-14 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_auto_20200908_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='organization',
            field=models.ForeignKey(default=34, on_delete=django.db.models.deletion.CASCADE, to='company.Organization'),
            preserve_default=False,
        ),
    ]
