# Generated by Django 2.2.5 on 2020-10-09 16:10

import django.contrib.postgres.fields.citext
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_auto_20200915_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=512, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.RegexValidator(regex='^[A-Za-z]+[A-Za-z\\d\\._\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor')], max_length=20),
        ),
    ]
