# Generated by Django 2.2.5 on 2020-10-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_auto_20201009_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companylogisticinfo',
            name='annaul_logistic_spend_currency',
            field=models.CharField(blank=True, choices=[('INR', 'INR'), ('USD', 'USD'), ('PES', 'PES'), ('AUS', 'AUS'), ('LKR', 'LKR')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='companylogisticinfo',
            name='annual_revenue_currency',
            field=models.CharField(blank=True, choices=[('INR', 'INR'), ('USD', 'USD'), ('PES', 'PES'), ('AUS', 'AUS'), ('LKR', 'LKR')], max_length=5, null=True),
        ),
    ]
