# Generated by Django 2.2.5 on 2020-10-27 11:24

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_auto_20201023_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companylogisticinfo',
            name='annual_logistic_spend',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='companylogisticinfo',
            name='annual_revenue',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
