# Generated by Django 2.2.5 on 2021-01-27 12:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_company_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='incorporation_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1970), django.core.validators.MaxValueValidator(2021)]),
        ),
    ]
