# Generated by Django 2.2.5 on 2021-02-10 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0020_auto_20210127_1241'),
        ('company', '0020_auto_20201223_1317'),
    ]

    operations = [
    ]