# Generated by Django 2.2.5 on 2020-04-01 07:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import login.managers.jwt_token_manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JwtToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor')], default='customer', max_length=255)),
                ('entity_id', models.IntegerField()),
                ('token_key', models.CharField(max_length=2048)),
                ('token_value', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('expire_timestamp', models.IntegerField()),
            ],
            options={
                'db_table': 'jwt_tokens',
                'unique_together': {('entity_type', 'entity_id')},
            },
            bases=(models.Model, login.managers.jwt_token_manager.JwtTokenManager),
        ),
    ]
