# Generated by Django 2.2.5 on 2020-05-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jwttoken',
            name='session_id',
            field=models.CharField(default='qwe', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='jwttoken',
            unique_together={('entity_type', 'entity_id', 'session_id')},
        ),
    ]
