# Generated by Django 2.2.7 on 2020-01-02 08:53

import currency.managers.currency_manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='system', max_length=512)),
                ('updated_by', models.CharField(default='system', max_length=512)),
                ('entity_type', models.CharField(max_length=255)),
                ('entity_id', models.IntegerField()),
                ('air_import_currency', models.CharField(default='INR', max_length=5)),
                ('air_export_currency', models.CharField(default='INR', max_length=5)),
                ('lcl_import_currency', models.CharField(default='INR', max_length=5)),
                ('lcl_export_currency', models.CharField(default='INR', max_length=5)),
                ('fcl_import_currency', models.CharField(default='INR', max_length=5)),
                ('fcl_export_currency', models.CharField(default='INR', max_length=5)),
            ],
            options={
                'db_table': 'currency_profiles',
            },
            bases=(models.Model, currency.managers.currency_manager.CurrencyManager),
        ),
    ]
