# Generated by Django 2.2.5 on 2020-01-22 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencyprofile',
            old_name='air_export_currency',
            new_name='air_currency',
        ),
        migrations.RenameField(
            model_name='currencyprofile',
            old_name='air_import_currency',
            new_name='fcl_currency',
        ),
        migrations.RenameField(
            model_name='currencyprofile',
            old_name='fcl_export_currency',
            new_name='lcl_currency',
        ),
        migrations.RemoveField(
            model_name='currencyprofile',
            name='fcl_import_currency',
        ),
        migrations.RemoveField(
            model_name='currencyprofile',
            name='lcl_export_currency',
        ),
        migrations.RemoveField(
            model_name='currencyprofile',
            name='lcl_import_currency',
        ),
    ]
