# Generated by Django 2.2.5 on 2020-08-03 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_currencyprofile_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyprofile',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
    ]
