# Generated by Django 2.2.5 on 2020-09-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_auto_20200803_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyprofile',
            name='air_currency',
            field=models.CharField(choices=[('INR', 'INR'), ('USD', 'USD'), ('PES', 'PES'), ('AUS', 'AUS'), ('LKR', 'LKR')], max_length=5),
        ),
        migrations.AlterField(
            model_name='currencyprofile',
            name='fcl_currency',
            field=models.CharField(choices=[('INR', 'INR'), ('USD', 'USD'), ('PES', 'PES'), ('AUS', 'AUS'), ('LKR', 'LKR')], max_length=5),
        ),
        migrations.AlterField(
            model_name='currencyprofile',
            name='lcl_currency',
            field=models.CharField(choices=[('INR', 'INR'), ('USD', 'USD'), ('PES', 'PES'), ('AUS', 'AUS'), ('LKR', 'LKR')], max_length=5),
        ),
    ]
