# Generated by Django 2.2.5 on 2020-03-03 09:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import port.managers.port_manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('state', '0001_initial'),
        ('country', '0001_initial'),
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='system', max_length=512)),
                ('updated_by', models.CharField(default='system', max_length=512)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default=None, max_length=255, null=True, validators=[django.core.validators.RegexValidator(regex='^[A-Za-z]+[A-Za-z\\d\\._\\s]+$')])),
                ('iata', models.CharField(blank=True, default=None, max_length=255, null=True, validators=[django.core.validators.RegexValidator(regex='^[A-Za-z]+[A-Za-z\\d\\._\\s]+$')])),
                ('name', models.CharField(default=None, max_length=255, unique=True, validators=[django.core.validators.RegexValidator(regex='^[A-Za-z]+[A-Za-z\\d\\._\\s]+$')])),
                ('type', models.CharField(choices=[('airport', 'Airport'), ('seaport', 'Seaport')], default='airport', max_length=50)),
                ('lat', models.FloatField(default=None, max_length=255)),
                ('lng', models.FloatField(default=None, max_length=255)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='city.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='country.Country')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='state.State')),
            ],
            options={
                'db_table': 'ports',
            },
            bases=(models.Model, port.managers.port_manager.PortManager),
        ),
    ]
