# Generated by Django 2.2.5 on 2020-01-20 07:16

import address.manager.address_manager
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('state', '0001_initial'),
        ('city', '0001_initial'),
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='system', max_length=512)),
                ('updated_by', models.CharField(default='system', max_length=512)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('entity_type', models.CharField(max_length=255)),
                ('entity_id', models.IntegerField()),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255, null=True)),
                ('pincode', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='city.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='country.Country')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='state.State')),
            ],
            options={
                'db_table': 'addresses',
            },
            bases=(models.Model, address.manager.address_manager.AddressManager),
        ),
    ]
