# Generated by Django 2.2.5 on 2020-01-20 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200120_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{6,10}$')]),
        ),
    ]
