# Generated by Django 2.2.5 on 2020-09-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0001_initial'),
        ('address', '0006_auto_20200221_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='airport_ids',
            field=models.ManyToManyField(blank=True, db_table='address_airport', related_name='address_airport', to='port.Port'),
        ),
        migrations.AddField(
            model_name='address',
            name='seaport_ids',
            field=models.ManyToManyField(blank=True, db_table='address_seaport', related_name='address_seaport', to='port.Port'),
        ),
    ]
