# Generated by Django 2.2.5 on 2020-09-08 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0007_auto_20200827_1449'),
        ('address', '0007_auto_20200902_1136'),
    ]

    operations = [
    ]
