# Generated by Django 2.2.5 on 2020-04-17 11:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyexpertise',
            name='container_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('20 GP', '20-GP'), ('40 GP', '40-GP'), ('20 Flat-Rack', '20-Flat-Rack'), ('40 Flat-Rack', '40-Flat-Rack'), ('20 OT', '20-OT'), ('40 OT', '40-OT'), ('20-Reefer', '20-Reefer'), ('20 Tank', '20-Tank'), ('40 HC', '40-HC'), ('45 HC', '45-HC')], default=None, max_length=255), blank=True, null=True, size=None),
        ),
    ]
