# Generated by Django 2.2.5 on 2020-07-13 11:21

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry_management', '0003_auto_20200428_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyexpertise',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='companyexpertise',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('kg', 'KG'), ('tonnes', 'TONS'), ('lbs', 'LBS')], default=None, max_length=255, null=True),
        ),
    ]
