# Generated by Django 2.2.5 on 2020-07-31 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry_management', '0004_auto_20200713_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyexpertise',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('kg', 'KG'), ('lbs', 'LBS')], default=None, max_length=255, null=True),
        ),
    ]
