# Generated by Django 2.2.5 on 2020-08-24 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry_management', '0005_auto_20200731_0941'),
        ('enquiry_management', '0005_auto_20200805_1357'),
    ]

    operations = [
    ]
