# Generated by Django 2.2.5 on 2020-11-05 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry_management', '0006_merge_20200824_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyexpertise',
            old_name='weight',
            new_name='max_weight',
        ),
    ]
