# Generated by Django 2.2.5 on 2020-04-09 06:23

import datetime
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import quote.managers.quote_manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0007_auto_20200221_0641'),
        ('port', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='system', max_length=512)),
                ('updated_by', models.CharField(default='system', max_length=512)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('shipment_terms', models.CharField(choices=[('door_to_door', 'Door To Door'), ('door_to_port', 'Door To Port'), ('port_to_door', 'Port To Door'), ('port_to_port', 'Port To Port')], max_length=255)),
                ('expected_delivery_date', models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2020, 4, 9))])),
                ('is_origin_custom', models.BooleanField(default=False)),
                ('is_destination_custom', models.BooleanField(default=False)),
                ('is_personal_courier', models.BooleanField(default=False)),
                ('is_commercial_courier', models.BooleanField(default=False)),
                ('po_number', models.CharField(blank=True, max_length=255, null=True)),
                ('no_of_suppliers', models.IntegerField(blank=True, null=True)),
                ('quote_deadline', models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2020, 4, 9))])),
                ('special_requirement', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('free_days_destination', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.Company')),
                ('drop_air_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='quote_drop_air_port', to='port.Port')),
                ('drop_sea_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='quote_drop_sea_port', to='port.Port')),
                ('pickup_air_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='quote_pickup_air_port', to='port.Port')),
                ('pickup_sea_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='quote_pickup_sea_port', to='port.Port')),
            ],
            options={
                'db_table': 'quotes',
            },
            bases=(models.Model, quote.managers.quote_manager.QuoteManager),
        ),
        migrations.CreateModel(
            name='QuoteTransportMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='system', max_length=512)),
                ('updated_by', models.CharField(default='system', max_length=512)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('transport_mode', models.CharField(choices=[('Air', 'Air'), ('LCL', 'LCL'), ('FCL', 'FCL'), ('Air_courier', 'Air Courier')], default=None, max_length=255)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quote.Quote')),
            ],
            options={
                'db_table': 'quote_transport_modes',
            },
            bases=(models.Model, quote.managers.quote_manager.QuoteTransportModeManager),
        ),
    ]
