# Generated by Django 2.2.5 on 2020-04-24 07:31

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0003_auto_20200423_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagedetails',
            name='drop_location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='package_details_drop_location', to='address.Address'),
        ),
        migrations.AlterField(
            model_name='packagedetails',
            name='pickup_location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='package_details_pickup_location', to='address.Address'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2020, 4, 24))]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_deadline',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2020, 4, 24))]),
        ),
    ]
