# Generated by Django 2.2.5 on 2020-04-28 15:25

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0004_auto_20200424_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagedetails',
            name='container_type',
            field=models.CharField(blank=True, choices=[('20GP', '20-GP'), ('40GP', '40-GP'), ('20Flat-Rack', '20-Flat-Rack'), ('40Flat-Rack', '40-Flat-Rack'), ('20OT', '20-OT'), ('40OT', '40-OT'), ('20Reefer', '20-Reefer'), ('40Reefer', '40-Reefer'), ('20Tank', '20-Tank'), ('40HC', '40-HC'), ('45HC', '45-HC')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2020, 4, 28))]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_deadline',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2020, 4, 28))]),
        ),
    ]
