# Generated by Django 2.2.5 on 2020-05-07 07:57

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
        ('quote', '0005_auto_20200428_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='special_requirement',
        ),
        migrations.AddField(
            model_name='quote',
            name='depreference',
            field=models.ManyToManyField(blank=True, db_table='quote_depreferences', related_name='quote_depreferences', to='transport.Transport'),
        ),
        migrations.AddField(
            model_name='quote',
            name='is_depreference',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='is_preference',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='packaging',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='palletization',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='preference',
            field=models.ManyToManyField(blank=True, db_table='quote_preferences', related_name='quote_preferences', to='transport.Transport'),
        ),
        migrations.AddField(
            model_name='quote',
            name='switch_awb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='switch_b_l',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quote',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2020, 5, 7))]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_deadline',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2020, 5, 7))]),
        ),
    ]
