# Generated by Django 2.2.5 on 2020-05-18 10:30

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_auto_20200221_1212'),
        ('port', '0001_initial'),
        ('quote', '0006_auto_20200507_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagedetails',
            name='drop_location_id',
        ),
        migrations.RemoveField(
            model_name='packagedetails',
            name='pickup_location_id',
        ),
        migrations.AddField(
            model_name='packagedetails',
            name='drop_air_port',
            field=models.ManyToManyField(blank=True, db_table='package_details_drop_air_port', related_name='package_details_drop_air_port', to='port.Port'),
        ),
        migrations.AddField(
            model_name='packagedetails',
            name='drop_location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='package_details_drop_location', to='address.Address'),
        ),
        migrations.AddField(
            model_name='packagedetails',
            name='drop_sea_port',
            field=models.ManyToManyField(blank=True, db_table='package_details_drop_sea_port', related_name='package_details_drop_sea_port', to='port.Port'),
        ),
        migrations.AddField(
            model_name='packagedetails',
            name='pickup_air_port',
            field=models.ManyToManyField(blank=True, db_table='package_details_pickup_air_port', default=None, related_name='package_details_pickup_air_port', to='port.Port'),
        ),
        migrations.AddField(
            model_name='packagedetails',
            name='pickup_location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='package_details_pickup_location', to='address.Address'),
        ),
        migrations.AddField(
            model_name='packagedetails',
            name='pickup_sea_port',
            field=models.ManyToManyField(blank=True, db_table='package_details_pickup_sea_port', related_name='package_details_pickup_sea_port', to='port.Port'),
        ),
        migrations.RemoveField(
            model_name='quote',
            name='drop_air_port',
        ),
        migrations.AddField(
            model_name='quote',
            name='drop_air_port',
            field=models.ManyToManyField(blank=True, db_table='quote_drop_air_port', related_name='quote_drop_air_port', to='port.Port'),
        ),
        migrations.RemoveField(
            model_name='quote',
            name='drop_sea_port',
        ),
        migrations.AddField(
            model_name='quote',
            name='drop_sea_port',
            field=models.ManyToManyField(blank=True, db_table='quote_drop_sea_port', related_name='quote_drop_sea_port', to='port.Port'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2020, 5, 18))]),
        ),
        migrations.RemoveField(
            model_name='quote',
            name='pickup_air_port',
        ),
        migrations.AddField(
            model_name='quote',
            name='pickup_air_port',
            field=models.ManyToManyField(blank=True, db_table='quote_pickup_air_port', related_name='quote_pickup_air_port', to='port.Port'),
        ),
        migrations.RemoveField(
            model_name='quote',
            name='pickup_sea_port',
        ),
        migrations.AddField(
            model_name='quote',
            name='pickup_sea_port',
            field=models.ManyToManyField(blank=True, db_table='quote_pickup_sea_port', related_name='quote_pickup_sea_port', to='port.Port'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_deadline',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2020, 5, 18))]),
        ),
    ]
