# Generated by Django 2.2.5 on 2020-05-27 09:37

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0008_auto_20200520_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='expected_arrival_date',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2020, 5, 27))]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2020, 5, 27))]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_deadline',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2020, 5, 27))]),
        ),
        migrations.AlterUniqueTogether(
            name='quotetransportmode',
            unique_together={('quote', 'transport_mode')},
        ),
    ]
