# Generated by Django 2.2.5 on 2020-07-14 12:05

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0009_auto_20200527_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedetails',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='packagedetails',
            name='temperature_unit',
            field=models.CharField(blank=True, choices=[('C', 'C'), ('F', 'F')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='expected_arrival_date',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2020, 7, 14))]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2020, 7, 14))]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_deadline',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2020, 7, 14))]),
        ),
    ]
