# Generated by Django 2.2.5 on 2020-07-23 16:39

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0011_auto_20200722_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedetails',
            name='cargo_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='packagedetails',
            name='consignee_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='packagedetails',
            name='container',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='container_package_details', to='quote.PackageDetails'),
        ),
        migrations.AddField(
            model_name='packagedetails',
            name='container_subtype',
            field=models.CharField(blank=True, choices=[('GP', 'GP'), ('FR', 'Flat-Rack'), ('OT', 'Open-Top'), ('RF', 'Reefer'), ('Tank', 'Tank'), ('HC', 'HC')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='packagedetails',
            name='is_fcl_container',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='packagedetails',
            name='shipper_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='packagedetails',
            name='commodity',
            field=models.ManyToManyField(blank=True, db_table='package_details_commodities', to='commodity.Commodity'),
        ),
        migrations.AlterField(
            model_name='packagedetails',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='expected_arrival_date',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2020, 7, 23))]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2020, 7, 23))]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_deadline',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2020, 7, 23))]),
        ),
    ]
