# Generated by Django 2.2.5 on 2020-07-29 12:10

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0012_auto_20200723_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagedetails',
            name='consignee_details',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(regex='^[A-Za-z\\d\\._\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='packagedetails',
            name='shipper_details',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(regex='^[A-Za-z\\d\\._\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='expected_arrival_date',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2020, 7, 29))]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2020, 7, 29))]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_deadline',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2020, 7, 29))]),
        ),
    ]
