# Generated by Django 2.2.5 on 2020-09-02 11:23

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0013_auto_20200729_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagedetails',
            name='drop_air_port',
        ),
        migrations.RemoveField(
            model_name='packagedetails',
            name='drop_sea_port',
        ),
        migrations.RemoveField(
            model_name='packagedetails',
            name='pickup_air_port',
        ),
        migrations.RemoveField(
            model_name='packagedetails',
            name='pickup_sea_port',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='drop_air_port',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='drop_sea_port',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='pickup_air_port',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='pickup_sea_port',
        ),
        migrations.AlterField(
            model_name='quote',
            name='expected_arrival_date',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date.today)]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date.today)]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_deadline',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date.today)]),
        ),
    ]
