# Generated by Django 2.2.5 on 2020-10-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0014_auto_20200902_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotetransportmode',
            name='transport_mode',
            field=models.CharField(choices=[('Air', 'Air'), ('LCL', 'LCL'), ('FCL', 'FCL'), ('Air_courier', 'Air Courier')], max_length=30),
        ),
    ]
