# Generated by Django 2.2.5 on 2021-01-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0015_auto_20201012_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quote_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
