# Generated by Django 2.2.5 on 2021-01-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0016_quote_quote_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='is_submit_quote',
            field=models.BooleanField(default=False),
        ),
    ]
