# Generated by Django 2.2.5 on 2021-01-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0017_quote_is_submit_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quote_no_counter',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
