# Generated by Django 2.2.5 on 2021-02-10 13:12

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0018_quote_quote_no_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedetails',
            name='handover_date',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date.today)]),
        ),
        migrations.AddField(
            model_name='packagedetails',
            name='invoice_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='packagedetails',
            name='invoice_value_currency',
            field=models.CharField(default='INR', max_length=5),
        ),
        migrations.AddField(
            model_name='packagedetails',
            name='is_order_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='packagedetails',
            name='order_ready_date',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date.today)]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_no_counter',
            field=models.IntegerField(default=0),
        ),
    ]
