# Generated by Django 2.2.5 on 2021-02-24 06:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0020_auto_20210211_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='po_number',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None),
        ),
    ]
