# Generated by Django 2.2.5 on 2021-03-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0021_auto_20210224_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='shipment_type',
            field=models.CharField(choices=[('import', 'import'), ('export', 'export'), ('third-country', 'third_country')], default='import', max_length=15),
        ),
    ]
