# Generated by Django 2.2.5 on 2020-02-04 14:02

import contact_person.managers.contact_person_manager
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import utils.validations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0005_merge_20200120_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='system', max_length=512)),
                ('updated_by', models.CharField(default='system', max_length=512)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(regex='^[A-Za-z\\d\\._\\s]+$')])),
                ('email', models.EmailField(default=None, max_length=254)),
                ('secondary_email', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, null=True, size=None)),
                ('contact_no', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, validators=[utils.validations.ContactNumberValidation.validate_contact_no])),
                ('landline_no_dial_code', models.CharField(default=None, max_length=12, null=True)),
                ('landline_no', models.CharField(blank=True, default=None, max_length=12, null=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(regex='\\d{10}')])),
                ('designation', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('type', models.CharField(choices=[('finance', 'Finance'), ('shipper_user', 'Shipper user'), ('consignee_user', 'Consignee user'), ('consignee_shipper_user', 'Consignee Shipper user')], default='finance', max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.Company')),
            ],
            options={
                'db_table': 'contact_persons',
            },
            bases=(models.Model, contact_person.managers.contact_person_manager.ContactPersonManager),
        ),
    ]
