# Generated by Django 2.2.5 on 2020-11-05 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_person', '0002_auto_20201103_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactperson',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(regex='^[A-Za-z]+[A-Za-z\\d\\._\\s]+$')]),
        ),
    ]
